import express from "express";
import cors from "cors";
import dotenv from "dotenv";
dotenv.config();
import { chatWithAI } from "./chatbot.js";
import pkg from "pdfkit";
import mealPlanRoute from "./routes/mealPlan.js";
import { generateMedicalSummary } from "./chatbot.js";
import {
  generateWeightChart,
  generateCaloriesChart,
} from "./util/chartGenerator.js";



import Groq from "groq-sdk";

export const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY,
});


console.log("GROQ KEY EXISTS:", !!process.env.GROQ_API_KEY);
process.on("unhandledRejection", (err) => {
  console.error("UNHANDLED PROMISE:", err);
});

process.on("uncaughtException", (err) => {
  console.error("UNCAUGHT EXCEPTION:", err);
});


const PDFDocument = pkg;
const app = express();
const PORT = 5000;

// -------------------- MIDDLEWARE --------------------
app.use(cors());
app.use(express.json());
app.use((req, res, next) => {
  console.log("➡️", req.method, req.url);
  next();
});
app.use("/api/meal-plan", mealPlanRoute);



// -------------------- HEALTH CHECK --------------------
app.get("/", (_, res) => {
  res.send("NutriScan backend running ");
});

// -------------------- MEAL  --------------------
app.post("/api/meal", async (req, res) => {
  const { remainingCals, userProfile } = req.body;
  const veg = userProfile?.dietType === "veg";

  res.json({
    name: veg ? "Paneer & Vegetable Bowl" : "Grilled Chicken with Vegetables",
    cals: Math.min(remainingCals || 400, 450),
    desc: veg
      ? "High-protein vegetarian meal with paneer and vegetables."
      : "Balanced non-veg meal with lean protein.",
    note: userProfile?.condition
      ? `Adjusted for ${userProfile.condition}`
      : null,
  });
});




// -------------------- CHATBOT  --------------------
app.post("/api/chat", async (req, res) => {
  try {
    const { message, profile } = req.body;
    const reply = await chatWithAI(message, profile);
    res.json({ reply });
  } catch (err) {
    console.error("Chat error:", err);
    res.status(500).json({ reply: "AI is unavailable right now." });
  }
});


// -------------------- PDF REPORT --------------------
app.post("/api/report/pdf", async (req, res) => {
  try {
    const { profile, nutrition } = req.body;

    // 🔹 AI Summary
    const summary = await generateMedicalSummary(profile, nutrition);

    // 🔹 Charts
    const weightChart = await generateWeightChart(profile.weight || 70);
    const calorieChart = await generateCaloriesChart(
      nutrition.calories || 0,
      nutrition.calories || 2000
    );

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=NutriScan_Medical_Report.pdf"
    );

    doc.pipe(res);

    // ---------- TITLE ----------
    doc.fontSize(20).text("NutriScan AI – Medical Report", { align: "center" });
    doc.moveDown(1.5);

    // ---------- PROFILE ----------
    doc.fontSize(14).text("Patient Profile", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(12)
      .text(`Name: ${profile.name}`)
      .text(`Age: ${profile.age}`)
      .text(`Sex: ${profile.sex}`)
      .text(`Height: ${profile.height} cm`)
      .text(`Weight: ${profile.weight} kg`)
      .text(`Condition: ${profile.condition || "None"}`)
      .text(`Goal: ${profile.goal}`);

    doc.moveDown();

    // ---------- NUTRITION ----------
    doc.fontSize(14).text("Daily Nutrition Summary", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(12)
      .text(`Calories: ${nutrition.calories} kcal`)
      .text(`Protein: ${nutrition.protein} g`)
      .text(`Fats: ${nutrition.fats} g`);

    doc.moveDown();

    // ---------- AI SUMMARY ----------
    doc.fontSize(14).text("AI Medical Summary", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(12).text(summary);
    doc.moveDown(1.5);

    // ---------- CHARTS ----------
    doc.fontSize(14).text("Weight Trend", { underline: true });
    doc.moveDown(0.5);
    doc.image(weightChart, { width: 450 });
    doc.moveDown();

    doc.fontSize(14).text("Calories Intake vs Goal", { underline: true });
    doc.moveDown(0.5);
    doc.image(calorieChart, { width: 450 });

    doc.moveDown(2);

    // ---------- FOOTER ----------
    doc.fontSize(10).text(
      "Generated by NutriScan AI. This report is for informational purposes only.",
      { align: "center" }
    );

    doc.end();
  } catch (err) {
    console.error(" PDF ERROR:", err);
    res.status(500).json({ error: "PDF generation failed" });
  }
});

app.post("/api/dinner", async (req, res) => {
  try {
    const { remainingCalories, dietType, condition, goal } = req.body;

    const prompt = `
You are a certified Indian nutritionist.

Generate ONE Indian dinner idea ONLY.

STRICT RULES:
- Cuisine: Indian food only (no pasta, pizza, salad, sandwich, soup)
- Diet type: ${dietType === "veg" ? "Pure vegetarian (no egg)" : "Non-vegetarian allowed"}
- Health condition: ${condition || "none"}
- Fitness goal: ${goal}
- Calories must be under ${remainingCalories}

SPECIAL HEALTH RULES:
${condition === "diabetes" ? "- Avoid sugar, white rice, refined flour. Prefer low-GI foods like millets, dal, vegetables.\n" : ""}
${condition === "hypertension" ? "- Low salt, avoid fried foods.\n" : ""}
${condition === "cholesterol" ? "- Low oil, avoid butter and cream.\n" : ""}

OUTPUT FORMAT (IMPORTANT):
Respond ONLY in valid JSON. No explanation text.

{
  "name": "Indian dish name",
  "cals": number,
  "desc": "Short 1-line description"
}
`;


    const reply = await chatWithAI(prompt);

    console.log("AI RAW DINNER REPLY:", reply);

    const meal = JSON.parse(reply);

    res.json(meal);
  } catch (err) {
    console.error(" Dinner AI error:", err.message);

    res.status(500).json({
      error: "AI dinner generation failed",
    });
  }
});


function isGenericQuery(query) {
  return query.trim().split(/\s+/).length <= 2;
}

app.post("/api/recipe", async (req, res) => {
  const { food, goal, condition } = req.body;

  if (!food) {
    return res.status(400).json({ error: "Food is required" });
  }

  try {
    const prompt = `
You are a nutrition recipe generator.

VERY IMPORTANT RULES:
- The user typed: "${food}"
- Use ONLY the main ingredient the user typed
- DO NOT introduce chicken, meat, or other proteins unless the user explicitly typed them
- If the input is generic (e.g. "rice", "pasta"), keep the recipe SIMPLE and VEGETARIAN
- Do NOT suggest "chicken and rice" unless the word "chicken" is in the input
- Do NOT change the dish concept

Return ONLY valid JSON.
No markdown. No explanation.

JSON format:
{
  "title": "string",
  "calories": number,
  "protein": number,
  "fats": number,
  "ingredients": string[],
  "instructions": string
}
`;


    const completion = await groq.chat.completions.create({
      model: "llama-3.1-8b-instant",
      messages,
      temperature: 0.2,
      max_tokens: 1200,
    });




    const raw = completion.choices[0].message.content;

    const jsonMatch = raw.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      console.error("RAW AI REPLY:", raw);
      throw new Error("No JSON in AI response");
    }

    res.json(JSON.parse(jsonMatch[0]));
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Recipe AI failed" });
  }
});

// -------------------- START SERVER --------------------
app.listen(PORT, () => {
  console.log(` Backend running at http://localhost:${PORT}`);
});
