import express from "express";
import cors from "cors";
import dotenv from "dotenv";
dotenv.config();
import { chatWithAI } from "./chatbot.js";
import pkg from "pdfkit";
import mealPlanRoute from "./routes/mealPlan.js";
import { generateMedicalSummary } from "./chatbot.js";
import {
  generateWeightChart,
  generateCaloriesChart,
} from "./util/chartGenerator.js";



import Groq from "groq-sdk";

export const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY,
});


console.log("GROQ KEY EXISTS:", !!process.env.GROQ_API_KEY);
process.on("unhandledRejection", (err) => {
  console.error("UNHANDLED PROMISE:", err);
});

process.on("uncaughtException", (err) => {
  console.error("UNCAUGHT EXCEPTION:", err);
});


const PDFDocument = pkg;
const app = express();
const PORT = 5000;

// -------------------- MIDDLEWARE --------------------
app.use(cors());
app.use(express.json());
app.use((req, res, next) => {
  console.log("➡️", req.method, req.url);
  next();
});
app.use("/api/meal-plan", mealPlanRoute);



// -------------------- HEALTH CHECK --------------------
app.get("/", (_, res) => {
  res.send("NutriScan backend running ");
});

// -------------------- MEAL  --------------------
app.post("/api/meal", async (req, res) => {
  const { remainingCals, userProfile } = req.body;
  const veg = userProfile?.dietType === "veg";

  res.json({
    name: veg ? "Paneer & Vegetable Bowl" : "Grilled Chicken with Vegetables",
    cals: Math.min(remainingCals || 400, 450),
    desc: veg
      ? "High-protein vegetarian meal with paneer and vegetables."
      : "Balanced non-veg meal with lean protein.",
    note: userProfile?.condition
      ? `Adjusted for ${userProfile.condition}`
      : null,
  });
});




// -------------------- CHATBOT  --------------------
app.post("/api/chat", async (req, res) => {
  try {
    const { message, profile } = req.body;
    const reply = await chatWithAI(message, profile);
    res.json({ reply });
  } catch (err) {
    console.error("Chat error:", err);
    res.status(500).json({ reply: "AI is unavailable right now." });
  }
});


// -------------------- PDF REPORT --------------------
app.post("/api/report/pdf", async (req, res) => {
  try {
    const { profile, nutrition } = req.body;

    // 🔹 AI Summary
    const summary = await generateMedicalSummary(profile, nutrition);

    // 🔹 Charts
    const weightChart = await generateWeightChart(profile.weight || 70);
    const calorieChart = await generateCaloriesChart(
      nutrition.calories || 0,
      nutrition.calories || 2000
    );

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=NutriScan_Medical_Report.pdf"
    );

    doc.pipe(res);

    // ---------- TITLE ----------
    doc.fontSize(20).text("NutriScan AI – Medical Report", { align: "center" });
    doc.moveDown(1.5);

    // ---------- PROFILE ----------
    doc.fontSize(14).text("Patient Profile", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(12)
      .text(`Name: ${profile.name}`)
      .text(`Age: ${profile.age}`)
      .text(`Sex: ${profile.sex}`)
      .text(`Height: ${profile.height} cm`)
      .text(`Weight: ${profile.weight} kg`)
      .text(`Condition: ${profile.condition || "None"}`)
      .text(`Goal: ${profile.goal}`);

    doc.moveDown();

    // ---------- NUTRITION ----------
    doc.fontSize(14).text("Daily Nutrition Summary", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(12)
      .text(`Calories: ${nutrition.calories} kcal`)
      .text(`Protein: ${nutrition.protein} g`)
      .text(`Fats: ${nutrition.fats} g`);

    doc.moveDown();

    // ---------- AI SUMMARY ----------
    doc.fontSize(14).text("AI Medical Summary", { underline: true });
    doc.moveDown(0.5);

    doc.fontSize(12).text(summary);
    doc.moveDown(1.5);

    // ---------- CHARTS ----------
    doc.fontSize(14).text("Weight Trend", { underline: true });
    doc.moveDown(0.5);
    doc.image(weightChart, { width: 450 });
    doc.moveDown();

    doc.fontSize(14).text("Calories Intake vs Goal", { underline: true });
    doc.moveDown(0.5);
    doc.image(calorieChart, { width: 450 });

    doc.moveDown(2);

    // ---------- FOOTER ----------
    doc.fontSize(10).text(
      "Generated by NutriScan AI. This report is for informational purposes only.",
      { align: "center" }
    );

    doc.end();
  } catch (err) {
    console.error(" PDF ERROR:", err);
    res.status(500).json({ error: "PDF generation failed" });
  }
});


app.post("/api/dinner", async (req, res) => {
  try {
    const { remainingCalories, condition, dietType } = req.body;

    if (!groq) {
      console.error("CRITICAL: Groq client is not initialized.");
      // Fallback immediately if AI isn't ready
      return res.json(getFallbackDinner(condition || "none", 400));
    }

    const safeCalories = Number(remainingCalories) > 0 ? Number(remainingCalories) : 400;
    const safeCondition = (condition || "none").toLowerCase().replace(/\s+/g, "");
    const safeDiet = dietType || "vegetarian";


    const completion = await groq.chat.completions.create({
      model: "llama-3.1-8b-instant",
      temperature: 0.3,
      messages: [
        {
          role: "system",
          content: "You are a nutritionist. Return ONLY valid JSON."
        },
        {
          role: "user",
          content: `Suggest ONE healthy Indian dinner under ${safeCalories} calories.
          
          Constraints:
          - Diet Type: ${safeDiet}
          - Condition: ${safeCondition} (avoid bad ingredients)
          
          Return ONLY JSON (no markdown):
          {
            "name": "Dish Name",
            "cals": number,
            "desc": "Short description"
          }`
        },
      ],
      max_tokens: 300,
    });

    const reply = completion.choices?.[0]?.message?.content || "";
    const jsonMatch = reply.match(/\{[\s\S]*\}/);

    if (!jsonMatch) {
      console.warn("⚠️ AI did not return JSON. Using fallback.");
      return res.json(getFallbackDinner(safeCondition, safeCalories));
    }

    const meal = JSON.parse(jsonMatch[0]);

    if (!meal.name || !meal.cals) {
      return res.json(getFallbackDinner(safeCondition, safeCalories));
    }

    res.json(meal);

  } catch (err) {
    console.error("❌ /api/dinner CRASHED:", err.message);
    if (err.message.includes("API key")) {
      console.error("💡 HINT: Check your .env file for GROQ_API_KEY");
    }
    const fallbackCals = req.body.remainingCalories || 400;
    res.json(getFallbackDinner("none", fallbackCals));
  }
});
function isGenericQuery(query) {
  return query.trim().split(/\s+/).length <= 2;
}

app.post("/api/recipe", async (req, res) => {
  const { food, goal, condition } = req.body;

  if (!food) {
    return res.status(400).json({ error: "Food is required" });
  }

  try {
    const prompt = `
You are a nutrition recipe generator.

VERY IMPORTANT RULES:
- The user typed: "${food}"
- Use ONLY the main ingredient the user typed
- DO NOT introduce chicken, meat, or other proteins unless the user explicitly typed them
- If the input is generic (e.g. "rice", "pasta"), keep the recipe SIMPLE and VEGETARIAN
- Do NOT suggest "chicken and rice" unless the word "chicken" is in the input
- Do NOT change the dish concept

Return ONLY valid JSON.
No markdown. No explanation.

JSON format:
{
  "title": "string",
  "calories": number,
  "protein": number,
  "fats": number,
  "ingredients": string[],
  "instructions": string
}
`;

    const completion = await groq.chat.completions.create({
      model: "llama-3.1-8b-instant",
      messages: [
        {
          role: "user",
          content: prompt,
        },
      ],
      temperature: 0.2,
      max_tokens: 1200,
    });

    const raw = completion.choices[0].message.content;

    const jsonMatch = raw.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      console.error("RAW AI REPLY:", raw);
      throw new Error("No JSON in AI response");
    }

    res.json(JSON.parse(jsonMatch[0]));
  } catch (err) {
    console.error("❌ Recipe AI error:", err);
    res.status(500).json({ error: "Recipe AI failed" });
  }
});


// -------------------- START SERVER --------------------
app.listen(PORT, () => {
  console.log(` Backend running at http://localhost:${PORT}`);
});
